services:
  web:
    build: .
    container_name: lana-8-wonder
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=uk.lana8wonder.com,si.lana8wonder.com,hu.lana8wonder.com,at.lana8wonder.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=uk.lana8wonder.com,si.lana8wonder.com,hu.lana8wonder.com,at.lana8wonder.com
      - NODE_ENV=production
      - PORT=3000
    networks:
      - webproxy

networks:
  webproxy:
    external: true
